# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Geometrybag
tagline:             'My Blog'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> My Blog All themes spatial by <a href="https://twitter.com/DomStubbins" target="_blank">@mdo</a>.'
url:                 http://dstubbin.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Dominic Stubbins
  url:               https://twitter.com/DomStubbins
  email:             DomStubbins@mail.com

# Custom vars
version:             1.0.0
